baseURL = "https://hesay.me/"
languageCode = "zh-cn"
title = "éš¾è¨€"
theme = "hugo-paper"

DisqusShortname = "hesay-me"

[author]
    name = "indes"
[params]
    description = "æˆ‘çœ‹è§çš„ä¸–ç•Œã€‚"
[menu]

  [[menu.main]]
    identifier = "about"
    name = "ğŸ‘¨ğŸ»â€ğŸš€About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  [[menu.main]]
    identifier = "link"
    name = "ğŸ”—Links"
    pre = "<i class='fa fa-heart'></i>"
    url = "/links/"
    weight = -120

  #[[menu.main]]
    #name = "getting started"
    #pre = "<i class='fa fa-road'></i>"
    #url = "/getting-started/"
    #weight = -100

enableRobotsTXT = true
canonifyURLs = true
# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"