baseURL = "https://hesay.net/"
languageCode = "zh-cn"
title = "HeSay"
theme = "hugo-paper"

DisqusShortname = "hesay"

[author]
    name = "indes"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "ğŸ“About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  #[[menu.main]]
    #name = "getting started"
    #pre = "<i class='fa fa-road'></i>"
    #url = "/getting-started/"
    #weight = -100