baseURL = "https://hesay.me/"
languageCode = "zh-cn"
title = "çè¯´"
theme = "hugo-paper"

# DisqusShortname = "hesay-me"

[author]
    name = "indes"
[params]
    AuthorName = "indes"
    GitHubUser = "indes"
    description = "æˆ‘çœ‹è§çš„ä¸–ç•Œã€‚"
[menu]

  [[menu.main]]
    identifier = "about"
    name = "ğŸ‘¨ğŸ»â€ğŸš€About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  [[menu.main]]
    identifier = "friends"
    name = "ğŸ”—Friends"
    pre = "<i class='fa fa-heart'></i>"
    url = "/friends/"
    weight = -120

  [[menu.main]]
    identifier = "disk"
    name = "ğŸ’¾Disk"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://disk.hesay.me/"
    weight = -130
  [[menu.main]]
    identifier = "disk"
    name = "ğŸ’¾Disk"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://disk.hesay.me/"
    weight = -130
  [[menu.main]]
    identifier = "disk"
    name = "ğŸ’¾Disk"
    pre = "<i class='fa fa-heart'></i>"
    url = "https://disk.hesay.me/"
    weight = -130

  #[[menu.main]]
    #name = "getting started"
    #pre = "<i class='fa fa-road'></i>"
    #url = "/getting-started/"
    #weight = -100

enableRobotsTXT = true
canonifyURLs = true
# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"
